name: Release
on: workflow_dispatch
jobs:
  reload-service:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/projects/sudent-tracker
    steps:
      - name: Stop service
        run: systemctl stop student_tracker_bot.service
      - name: Pull master
#        env:
#          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
#          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
#          GITHUB_TOKEN: ${{ github.token }}
        run: git fetch https://${{ github.token }}@github.com/Mdau5h/sudent-tracker.git
#        run: echo $GITHUB_TOKEN
      - name: Resolve dependencies
        run: pipenv install
      - name: Start service
        run: systemctl start student_tracker_bot.service