name: Release
on: workflow_dispatch
jobs:
  reload-service:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/projects/sudent-tracker
    steps:
      - name: Stop service
        run: systemctl stop student_tracker_bot.service
      - name: Pull master
        run: git fetch
      - name: Resolve dependencies
        run: pipenv install
      - name: Start service
        run: systemctl start student_tracker_bot.service